"""Add unique indexes for upsert

Revision ID: 0bb39e3c5f1d
Revises: b4cf71c1fb0a
Create Date: 2026-06-09 22:23:03.868888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb39e3c5f1d'
down_revision: Union[str, None] = 'b4cf71c1fb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundamentals_symbol_date'), table_name='fundamentals')
    op.create_index('ix_fundamentals_symbol_date_category', 'fundamentals', ['symbol', 'date', 'category'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fundamentals_symbol_date_category', table_name='fundamentals')
    op.create_index(op.f('ix_fundamentals_symbol_date'), 'fundamentals', ['symbol', 'date'], unique=False)
    # ### end Alembic commands ###
