"""Flexible fundamentals with JSONB data

Revision ID: a472476141c8
Revises: 635b211e3001
Create Date: 2026-06-09 22:00:24.861580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a472476141c8'
down_revision: Union[str, None] = '635b211e3001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamentals', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('fundamentals', sa.Column('data', sa.Text(), nullable=False))
    op.create_index(op.f('ix_fundamentals_category'), 'fundamentals', ['category'], unique=False)
    op.create_index('ix_fundamentals_symbol_date', 'fundamentals', ['symbol', 'date'], unique=False)
    op.drop_column('fundamentals', 'market_cap')
    op.drop_column('fundamentals', 'extra')
    op.drop_column('fundamentals', 'eps')
    op.drop_column('fundamentals', 'sector')
    op.drop_column('fundamentals', 'net_income')
    op.drop_column('fundamentals', 'pb_ratio')
    op.drop_column('fundamentals', 'pe_ratio')
    op.drop_column('fundamentals', 'industry')
    op.drop_column('fundamentals', 'dividend_yield')
    op.drop_column('fundamentals', 'revenue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamentals', sa.Column('revenue', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('dividend_yield', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('pe_ratio', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('pb_ratio', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('net_income', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('eps', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('extra', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('fundamentals', sa.Column('market_cap', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True))
    op.drop_index('ix_fundamentals_symbol_date', table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_category'), table_name='fundamentals')
    op.drop_column('fundamentals', 'data')
    op.drop_column('fundamentals', 'category')
    # ### end Alembic commands ###
