"""Simplify to single adjustor_factor

Revision ID: b4cf71c1fb0a
Revises: f4b1c23b698e
Create Date: 2026-06-09 22:05:00.688091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4cf71c1fb0a'
down_revision: Union[str, None] = 'f4b1c23b698e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlc', sa.Column('adjustor_factor', sa.Numeric(precision=12, scale=8), nullable=False))
    op.drop_column('ohlc', 'adjusted_close')
    op.drop_column('ohlc', 'dividend_amount')
    op.drop_column('ohlc', 'split_factor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlc', sa.Column('split_factor', sa.NUMERIC(precision=12, scale=8), autoincrement=False, nullable=True))
    op.add_column('ohlc', sa.Column('dividend_amount', sa.NUMERIC(precision=12, scale=8), autoincrement=False, nullable=True))
    op.add_column('ohlc', sa.Column('adjusted_close', sa.NUMERIC(precision=18, scale=8), autoincrement=False, nullable=True))
    op.drop_column('ohlc', 'adjustor_factor')
    # ### end Alembic commands ###
