"""Rename adjustor_factor to backward_factor

Revision ID: eee7ba5183d8
Revises: 0bb39e3c5f1d
Create Date: 2026-06-09 22:47:11.743209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eee7ba5183d8'
down_revision: Union[str, None] = '0bb39e3c5f1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlc', sa.Column('backward_factor', sa.Numeric(precision=18, scale=10), nullable=False))
    op.drop_column('ohlc', 'adjustor_factor')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlc', sa.Column('adjustor_factor', sa.NUMERIC(precision=12, scale=8), autoincrement=False, nullable=False))
    op.drop_column('ohlc', 'backward_factor')
    # ### end Alembic commands ###
