"""OHLC adjustments and flexible data

Revision ID: f4b1c23b698e
Revises: a472476141c8
Create Date: 2026-06-09 22:02:54.411599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b1c23b698e'
down_revision: Union[str, None] = 'a472476141c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ohlc', sa.Column('adjusted_close', sa.Numeric(precision=18, scale=8), nullable=True))
    op.add_column('ohlc', sa.Column('split_factor', sa.Numeric(precision=12, scale=8), nullable=True))
    op.add_column('ohlc', sa.Column('dividend_amount', sa.Numeric(precision=12, scale=8), nullable=True))
    op.add_column('ohlc', sa.Column('data', sa.Text(), nullable=True))
    op.create_index('ix_ohlc_symbol_timeframe_timestamp', 'ohlc', ['symbol', 'timeframe', 'timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ohlc_symbol_timeframe_timestamp', table_name='ohlc')
    op.drop_column('ohlc', 'data')
    op.drop_column('ohlc', 'dividend_amount')
    op.drop_column('ohlc', 'split_factor')
    op.drop_column('ohlc', 'adjusted_close')
    # ### end Alembic commands ###
